[general]
model_name = "nemo4"
xml_path = "nemo4/scene.xml"

[weights]
velocity_weight = 3.0
angvel_z_weight = 2.0
angvel_xy_weight = -0.15
vel_z_weight = -0.01
energy_weight = -0.001
action_rate_weight = -0.01
upright_weight = 1.0
feet_slip_weight = -0.25
periodic_weight = 2.0
limit_weight = 5.0
flatfoot_weight = 4.0
feet_z_limit_weight = 4.0
feet_z_track_weight = 0.5
feet_zd_weight = 1.0
feet_orien_weight = 0.25
feet_slip_ang_weight = -0.25
halt_weight = 6.0
foot_col_weight = 10.0
knee_weight = -30.0


[train_func_parameters]
train_func_num_timesteps_const = 300000000
train_func_num_evals_const = 20 
train_func_episode_length_const = 1000
train_func_normalize_observations_bool = false
train_func_unroll_length_const = 20
train_func_num_minibatches_const = 32
train_func_num_updates_per_batch_const = 4
train_func_discounting_const = 0.97
train_func_learning_rate_const = 0.00005 
train_func_entropy_cost_const = 0.005
train_func_num_envs_const = 8192
train_func_batch_size_const = 256
train_func_clipping_epsilon_const = 0.2
train_func_num_resets_per_eval_const = 1
train_func_action_repeat_const = 1
train_func_max_grad_norm_const = 1.0
train_func_reward_scaling_const = 1.0
