[general]
model_name = "nemo4"
xml_path = "nemo4/scene.xml"

[weights]
velocity_weight = 4.0
angvel_z_weight = 4.0
angvel_xy_weight = -0.15
vel_z_weight = -0.01
energy_weight = -0.001
action_rate_weight = -0.01
upright_weight = 2.0
feet_slip_weight = -0.25
periodic_weight = 2.0
limit_weight = 2.0
flatfoot_weight = 8.0
feet_z_limit_weight = 4.0
feet_z_track_weight = 0.5
feet_zd_weight = 0.5
feet_orien_weight = 0.25
feet_slip_ang_weight = -0.25
halt_weight = 6.0
foot_col_weight = 10.0
knee_weight = -30.0


[train_func_parameters]
num_timesteps = 300000000
num_evals = 20 
episode_length = 1000
normalize_observations = false
unroll_length = 20
num_minibatches = 32
num_updates_per_batch = 4
discounting = 0.97
learning_rate = 0.00005 
entropy_cost = 0.005
num_envs = 8192
clipping_epsilon = 0.2
batch_size = 256
num_resets_per_eval = 1
action_repeat = 1
max_grad_norm = 1.0
reward_scaling = 1.0
